export const initialTasks = [
  {
    id: 1,
    title: "Launch Epic Career \u{1F680}",
    description: "",
    status: "todo",
    priority: "low",
  },
  {
    id: 2,
    title: "Conquer React \u267B\uFE0F",
    description: "",
    status: "todo",
    priority: "low",
  },
  {
    id: 3,
    title: "Understand Databases \u2699\uFE0F",
    description: "",
    status: "todo",
    priority: "low",
  },
  {
    id: 4,
    title: "Crush Frameworks \u{1F9E9}",
    description: "",
    status: "todo",
    priority: "low",
  },
  {
    id: 5,
    title: "Master JavaScript \u{1F49B}",
    description: "",
    status: "doing",
    priority: "high",
  },
  {
    id: 6,
    title: "Never Give Up \u{1F3C6}",
    description: "",
    status: "doing",
    priority: "medium",
  },
  {
    id: 7,
    title: "Explore ES6 Features \u{1F680}",
    description: "",
    status: "done",
    priority: "medium",
  },
  {
    id: 8,
    title: "Have fun \u{1F929}",
    description: "",
    status: "done",
    priority: "low",
  },
];
